### PR TITLE
Added a CGI-bin example

### PR DESCRIPTION
**Pull request by stappersg**
It is the working example I wish I had when I started.
Now available for the merecat CGI-bin starters after me.

new file:   www/cgi-bin/onboard_ask.py
new file:   www/onboard/form.html
new file:   www/onboard/file/placeholder.text

### CODE REVIEW

**Comment by troglobit** [comment]
Great idea, here are a few comments that need to be addressed before merging:

 1. Please replace rms with jef instead in all examples, long name Jef Poskanzer, I do not want this project to be associated in any way with Stallman
 2. Please add the files to the build system, otherwise they are just part of GIT not the generated tarballs.
 3. Please drop, or change, the content of the placeholder to something else, just hinting of ssh keys brings security "researchers" to the yard ... as it is now it's also placed in the root folder of the tree, which cannot be right?

**Comment by troglobit** [comment]
Since you changed the title of this PR to "WIP", I'll wait for you to either drop that or let me know when you're finished. (The PR title is used in the merge commit.)

**Comment by stappersg** [comment]
The _Work In Progress_ marker is removed.

Regarding
> just hinting of ssh keys brings security "researchers" to the yard ...

I'm looking forward to be lecutered by a security "researcher" about the riscs of exchanging _public part_ of a SSH-key.

**Comment by troglobit** [comment]
Thanks, merging! I may refactor this example slightly later on.

**Pull request merged**
